import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import {AosInit} from '../components/aos-init';
import "./styles.css";
const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100", "200", "300", "400", "500", "600", "700", "800", "900"
  ]
})

export const metadata: Metadata = {
  title: "Luis Martins",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={poppins.className}>
        {children}
        <AosInit/>
      </body>
    </html>
  );
}
